Repository gorakhargosh/watchdog, pull requests merged in 2019-12, with the labels that each got.

#597 Added parameter `ignore_device` to constructor of DirectorySnapshotDiff.
  src/watchdog/utils/dirsnapshot.py
  tests/test_snapshot_diff.py
Labels: dirsnapshot

#601 Fix a TypeError when deleting the watched folder on Windows
  src/watchdog/observers/winapi.py
  tests/test_observers_winapi.py
Labels: bug, windows

#603 Update the changelog
  changelog.rst
Labels: documentation

#602 [snapshot] Removed the walker_callback argument
  changelog.rst
  src/watchdog/observers/kqueue.py
  src/watchdog/utils/dirsnapshot.py
  tests/test_snapshot_diff.py
Labels: bug
