Repository gorakhargosh/watchdog, pull requests merged in 2020-02, with the labels that each got.

#629 Fixed the build_ext command on macOS Catalina
  changelog.rst
  setup.py
Labels: bug, fsevents-c

#636 Added FreeBSD CI support
  .cirrus.yml
  changelog.rst
  requirements-tests.txt
  tox.ini
Labels: kqueue

#640 [tests] Mark tests from test_delayed_queue.py as flaky
  tests/test_delayed_queue.py
Labels: improvement

#641 [BSD] Restore support
  changelog.rst
  src/watchdog/observers/kqueue.py
Labels: bug, kqueue

#642 Removed pinned macOS requirements for fsevents2
  changelog.rst
  setup.cfg
  setup.py
  tests/test_emitter.py
Labels: bug
