Repository gorakhargosh/watchdog, pull requests merged in 2020-07, with the labels that each got.

#677 Replace mutable default arguments with the correct implementation.
  changelog.rst
  src/watchdog/events.py
Labels: bug

#676 Add logger parameter for the LoggingEventHandler.
  changelog.rst
  src/watchdog/events.py
Labels: improvement

#678 Fix documentation
  docs/requirements.txt
Labels: bug, documentation
