Repository gorakhargosh/watchdog, pull requests merged in 2020-01, with the labels that each got.

#616 Fix Python 3.6 installation when the OS locale is set to POSIX
  changelog.rst
  setup.py
Labels: bug

#621 Add LC_ALL=C to Python 3.6 test on GNU/Linux
  .travis.yml
  changelog.rst
  src/watchdog/utils/dirsnapshot.py
  tests/test_snapshot_diff.py
Labels: bug, documentation

#622 Fix the build_ext command on macOS
  changelog.rst
  setup.cfg
  setup.py
  src/watchdog_fsevents.c
  tox.ini
Labels: bug, fsevents-c

#624 [mac] add -Wno-nullability-completeness to compilation arguments
  setup.py
Labels: bug, fsevents-c

#626 Bump the version to 0.10.2
  README.rst
  changelog.rst
  docs/source/conf.py
  src/watchdog/version.py
Labels: documentation
