Repository gorakhargosh/watchdog, pull requests merged in 2020-10, with the labels that each got.

#681 Remove unused prototype
  src/watchdog_fsevents.c
Labels: fsevents-c, improvement

#688 Add watchdog.tricks to the API documentation
  docs/source/api.rst
  src/watchdog/tricks/__init__.py
Labels: bug, documentation

#680 Performance improvements for the `fsevents` module
  changelog.rst
  src/watchdog/observers/fsevents.py
  src/watchdog_fsevents.c
Labels: fsevents-c, improvement

#691 Expand tests to Python 2.7 and 3.5-3.10 for GNU/Linux, macOS and Windows
  .travis.yml
  .travis/install.sh
  changelog.rst
Labels: improvement

#698 [mac] Prevent compilation of watchdog_fsevents.c on non-macOS machines
  changelog.rst
  setup.py
Labels: fsevents-c
